### ISSUE TITLE
LineWalkerをWalkerから継承させる

### ISSUE THREAD

**Issue by owhinata** [owhinata/etrobo_tr_ex3#16]

**Comment by KodoRisei** [comment]
- SampleWalkerを参考にする
 - getClassName()→クラス名を文字列で返す

**Comment by owhinata** [comment]
@KodoRisei さん
こちらの作業は、シナリオ切り替えの修正量が多いので、　https://github.com/owhinata/etrobo_tr_ex3/pull/17 をマージした状態で作業を行ったほうが問題起きないと思います。
あと、小堂さんのPCで動作確認できないようでしたら、ビルドを通したものをfeatureブランチにあげてもらえれば自分の方で動作確認しようかと思います。

**Comment by owhinata** [comment]
> ## memo
> * SampleWalkerを参考にする
> * getClassName()→クラス名を文字列で返す

ちなみにgetClassName()は scenario.jsonの　↓ と比較するために使う予定です。
https://github.com/owhinata/etrobo_tr_ex3/blob/feature/scenario/%2314/scenario.json#L11

**Comment by KodoRisei** [comment]
@owhinata さん
>https://github.com/owhinata/etrobo_tr_ex3/pull/17 をマージした状態で作業を行ったほうが問題起きないと思います。
承知しました。

動作確認の件は、現在自分のPCで環境設定中です。
ダメそうでしたらお願いします。

**Comment by KodoRisei** [comment]
@owhinata さん
自分のPCで現在のmainブランチがスムーズに動くことを確認できたので、こちらで進めて参ります。

**Comment by owhinata** [comment]
@KodoRisei さん
東門さんから聞いたかもですが、小堂さんが今日は通常業務ってことて、こちらのタスクを自分のほうで引き取ろうかと思います。 
現状で、何かしら手をつけているようだと、それを引き継いで作業していくので gitに上げておいてもらえると助かります。

**Comment by KodoRisei** [comment]
@owhinata さん
承知しました。
現状、特に何も手を付けられていない状態です。
よろしくお願いいたします。
